# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
