# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookmark_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='new_url',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
